### ISSUE TITLE
Could not get unknown property 'lintVersion'

### ISSUE THREAD

**Issue by johnnyzen** [google/android-security-lints#1]
Added checks library and getting "Could not get unknown property 'lintVersion'"

No indication if I need to provide this in documentation?

**Comment by bjiang7** [comment]
Hey johnnyzen, just checking if you've first tried adding the lintVersion to your app's build.gradle file (see here for an example: https://github.com/google/android-security-lints/blob/main/build.gradle#L21).

Happy to update the documentation if this was confusing and resolves your issue.

**Comment by bjiang7** [comment]
Also just to clarify, did you make sure to include the [build.gradle file](https://github.com/google/android-security-lints/blob/main/checks/build.gradle) included within the checks/ directory?

**Comment by johnnyzen** [comment]
aha, i missed the ext section, thanks for pointing out. :)
