### ISSUE TITLE
Publication on gMaven requires JDK21+

### ISSUE THREAD

**Issue by jozuasijsling-ing** [google/android-security-lints#6]
Presumably, this requirement isn't intentional. I did some testing and found two distinct errors depending on AGP version used and whether or not `ext.lintVersion` is specified as documented:

Error ❌<sup>1</sup>:
> Could not load custom lint check jar file [..]/com.android.security.lint/lint/1.0.0/a0d1f9c8ecd5f10d136e1be580ff6e0bc3f6ae2a/lint-1.0.0.jar
java.lang.UnsupportedClassVersionError: com/example/lint/checks/IssueRegistry has been compiled by a more recent version of the Java Runtime (class file version 65.0), this version of the Java Runtime only recognizes class file versions up to 61.0

Error ❌<sup>2</sup>:
> Error verifying bytecode in [...]/com.android.security.lint/lint/1.0.0/a0d1f9c8ecd5f10d136e1be580ff6e0bc3f6ae2a/lint-1.0.0.jar
java.lang.IllegalArgumentException: Unsupported class file major version 65

| AGP | JDK | ext.lintVersion | Result |
|-|-|-|-|
| 8.5.2 | 17 | <sub>unspecified</sub> | ❌<sup>1</sup> |
| | | $${\color{green}"31.5.1"}$$ | ❌<sup>1</sup> |
| | 21 | <sub>unspecified</sub> | ✅ |
| | | $${\color{green}"31.5.1"}$$ | ✅ |
| 8.5.0 | 17 | <sub>unspecified</sub> | ❌<sup>1</sup> |
| | | $${\color{green}"31.5.1"}$$ | ❌<sup>1</sup> |
| | 21 | <sub>unspecified</sub>| ✅ |
| | | $${\color{green}"31.5.1"}$$ | ✅ |
| 8.4.0 | 17 | <sub>unspecified</sub>| ❌<sup>1</sup> |
| | | $${\color{green}"31.5.1"}$$ | ❌<sup>1</sup> |
| | 21 | <sub>unspecified</sub> | ✅ |
| | | $${\color{green}"31.5.1"}$$ | ✅ |
| 8.2.1 | 17 | <sub>unspecified</sub> | ❌<sup>1</sup> |
| | | $${\color{green}"31.5.1"}$$ | ❌<sup>1</sup> |
| | 21 | <sub>unspecified</sub> | ❌<sup>2</sup> |
| | | $${\color{green}"31.5.1"}$$  | ✅ |

**Comment by bjiang7** [comment]
Hey jozuasijsling-ing@, thanks for opening the issue. You're absolutely right, I must've compiled the library with a newer JDK version. I've now reuploaded it after compiling it with JDK 17, and you can access this with version 1.0.1.

Let me know if you're still having issues after trying the new version (I'll leave this issue open for you to close, once you confirm the issue is actually fixed). 

Thanks for trying out the android-security-lints library :D

**Comment by jozuasijsling-ing** [comment]
Works for me! Thanks @bjiang7.
